baseURL: "https://nydisabilityrightsarchive.org/"
languageCode: en-us
title: New York Disability Rights Archive
canonifyURLs: true
relativeURLs: true
capitalizeListTitles: false
disablePathToLower: true
assetDir: "assets"
ignoreLogs: "warning-goldmark-raw-html"
params:
  imagesFolder: /img
  images:
  description: 

menu:
  main:
  - name: Introduction
    pageRef: /introduction
    weight: 1
  - name: Topics
    pageRef: /topics
    weight: 2

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      footnoteprefix: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      fn_id_prefix: 'title'
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

defaultContentLanguage: en

mediaTypes:
  application/atom:
    suffixes:
    - xml

imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 85
  resampleFilter: box

module:
  #imports:
  #  - path: github.com/gohugoio/hugo-mod-bootstrap-scss/v5
  mounts:
    - source: assets
      target: assets
    - source: node_modules/bootstrap/scss
      target: assets/scss/bootstrap


# relativeURLs: true

build:
  list: always
  single: always
  publishResources: true
  render: always

pagination:
  pagerSize: 20
summaryLength: 7

outputs:
  home:
  - html
  - rss
  - json

taxonomies:
  category: categories
  tag: tags

timeout: 60000

related:
  includeNewer: true
  threshold: 90
  toLower: false
  indices:
    - name: title
      weight: 30
    - name: date
      weight: 20
    - name: eventname
      weight: 50
