name: Deploy to web

on:
  push:
    branches:
      - main # or whatever you call your production branch

env:
  DART_SASS_VERSION: 1.80.0
  HUGO_VERSION: 0.149.0 # will get Extended Version below
  PAGEFIND_VERSION: 1.1.1
  NODE: true
  # if you have other environment variables,
  # enter them here in similar fashion

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v7
      - name: Download Hugo v${{ env.HUGO_VERSION }}
        run: wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb -O hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb
      - name: Install Hugo v${{ env.HUGO_VERSION }}
        run: sudo dpkg -i hugo*.deb
      - name: Download Dart Sass v${{ env.DART_SASS_VERSION }}
        run: curl -LJO https://github.com/sass/dart-sass/releases/download/${{ env.DART_SASS_VERSION }}/dart-sass-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz
      - name: Unpack Dart Sass v${{ env.DART_SASS_VERSION }}
        run: |
          tar -xvf dart-sass-${{ env.DART_SASS_VERSION }}-linux-x64.tar.gz
          dart-sass/sass --embedded --version          
      - name: Add to the PATH
        run: echo "$GITHUB_WORKSPACE/dart-sass" >> $GITHUB_PATH
      - name: "npm ci"
        run: npm ci
      - name: "sass permission"
        run: npm run grant-permiso
      - name: "hugo build"
        run: hugo --gc --cleanDestinationDir --minify
      - name: Run Pagefind
        run: npx -y pagefind --site public
      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy public --project-name archive-wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}